# =============================================================
#  ██╗  ██╗███████╗███╗   ██╗███╗   ███╗███████╗ ██████╗
#  ╚██╗██╔╝██╔════╝████╗  ██║████╗ ████║██╔════╝██╔════╝
#  ╚ ███╔╝ █████╗  ██╔██╗ ██║██╔████╔██║███████╗██║  ███╗
#   ██╔██╗ ██╔══╝  ██║╚██╗██║██║╚██╔╝██║╚════██║██║   ██║
#  ██╔╝ ██╗███████╗██║ ╚████║██║ ╚═╝ ██║███████║╚██████╔╝
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝     ╚═╝╚══════╝ ╚═════╝
# =============================================================
# Authors: XenVision, okunivaxx [TGK: t.me/xen_vision]
# XenVision © 2025, All rights reserved
# This plugin is developed and maintained by XenVision
# Description: Конфигурация для плагина XenMSG
# -------------------------------------------------------------
# WARNING: storage-method: YAML & MYSQL
# -------------------------------------------------------------
messages-file: messages.yml # Файл с сообщениями
storage-method: YAML # Метод хранения отправленных сообщений игрокам офлайн
mysql: # Данные датабазы
  host: localhost
  database: xenmsg
  user: root
  password: ""
